// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Convert(arg1, arg2) {
  return window['go']['convert3mf']['Convert3mf']['Convert'](arg1, arg2);
}

export function ConvertMany(arg1, arg2, arg3) {
  return window['go']['convert3mf']['Convert3mf']['ConvertMany'](arg1, arg2, arg3);
}
