// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {convert3mf} from '../models';

export function Convert(arg1:string,arg2:string):Promise<void>;

export function ConvertMany(arg1:string,arg2:Array<string>,arg3:string):Promise<{[key: string]: convert3mf.status}>;
