// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Hoist(arg1, arg2, arg3) {
  return window['go']['hoistfiles']['HoistFiles']['Hoist'](arg1, arg2, arg3);
}
