// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckMany(arg1, arg2) {
  return window['go']['stlintegrity']['STLIntegrity']['CheckMany'](arg1, arg2);
}

export function CheckSTL(arg1) {
  return window['go']['stlintegrity']['STLIntegrity']['CheckSTL'](arg1);
}
