// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {stlintegrity} from '../models';

export function CheckMany(arg1:string,arg2:Array<string>):Promise<{[key: string]: stlintegrity.status}>;

export function CheckSTL(arg1:string):Promise<boolean>;
