// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {manifest} from '../models';

export function ConvertTagsToAttributes(arg1:string,arg2:string,arg3:Array<string>):Promise<Array<manifest.attrStatus>>;

export function FindAttributeKeys(arg1:string):Promise<Array<string>>;

export function PreviewReplaceKeys(arg1:Array<string>,arg2:string,arg3:string):Promise<{[key: string]: string}>;

export function ReplaceKeys(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<Array<manifest.status>>;
