// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertTagsToAttributes(arg1, arg2, arg3) {
  return window['go']['manifest']['Attributes']['ConvertTagsToAttributes'](arg1, arg2, arg3);
}

export function FindAttributeKeys(arg1) {
  return window['go']['manifest']['Attributes']['FindAttributeKeys'](arg1);
}

export function PreviewConvertTagsToAttributes(arg1, arg2, arg3) {
  return window['go']['manifest']['Attributes']['PreviewConvertTagsToAttributes'](arg1, arg2, arg3);
}

export function PreviewReplaceKeys(arg1, arg2, arg3) {
  return window['go']['manifest']['Attributes']['PreviewReplaceKeys'](arg1, arg2, arg3);
}

export function ReplaceKeys(arg1, arg2, arg3, arg4) {
  return window['go']['manifest']['Attributes']['ReplaceKeys'](arg1, arg2, arg3, arg4);
}
