// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {manifest} from '../models';

export function ConvertTagsToAttributes(arg1:string,arg2:string,arg3:Array<string>):Promise<Array<manifest.attrStatus>>;
