// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllManifests(arg1) {
  return window['go']['manifest']['Manifest']['GetAllManifests'](arg1);
}

export function MigrateManifests(arg1) {
  return window['go']['manifest']['Manifest']['MigrateManifests'](arg1);
}

export function ReadManifest(arg1) {
  return window['go']['manifest']['Manifest']['ReadManifest'](arg1);
}

export function WriteManifest(arg1, arg2) {
  return window['go']['manifest']['Manifest']['WriteManifest'](arg1, arg2);
}
