// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FindTags(arg1) {
  return window['go']['manifest']['Tags']['FindTags'](arg1);
}

export function PreviewReplace(arg1, arg2, arg3) {
  return window['go']['manifest']['Tags']['PreviewReplace'](arg1, arg2, arg3);
}

export function ReplaceTags(arg1, arg2, arg3, arg4) {
  return window['go']['manifest']['Tags']['ReplaceTags'](arg1, arg2, arg3, arg4);
}
