// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {folderexploder} from '../models';

export function Explode(arg1:string):Promise<{[key: string]: folderexploder.status}>;
