// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Explode(arg1) {
  return window['go']['folderexploder']['Exploder']['Explode'](arg1);
}

export function ExplodeList(arg1, arg2, arg3, arg4) {
  return window['go']['folderexploder']['Exploder']['ExplodeList'](arg1, arg2, arg3, arg4);
}

export function Prepare(arg1, arg2, arg3) {
  return window['go']['folderexploder']['Exploder']['Prepare'](arg1, arg2, arg3);
}
