// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {folderexploder} from '../models';

export function Explode(arg1:string):Promise<{[key: string]: folderexploder.status}>;

export function ExplodeList(arg1:string,arg2:Array<string>,arg3:string,arg4:string):Promise<{[key: string]: folderexploder.status}>;

export function Prepare(arg1:Array<string>,arg2:string,arg3:string):Promise<{[key: string]: Array<string>}>;

export function PreviewExplode(arg1:Array<string>,arg2:string,arg3:string):Promise<{[key: string]: string}>;
