name: build-stlm-helper
on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  build_release:
    strategy:
      matrix:
        # os: [ubuntu-22.04, macos-latest, windows-latest]
        # os: [macos-latest]
        os: [windows-latest]
        # os: [ubuntu-22.04]
    name: Build and release
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    steps:
      # Pull the code
      - name: Checkout client
        uses: actions/checkout@v4

      # Build
      # setup-go@v5 is built off the node20 runtime container
      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Install wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Install frontend dependencies
        run: cd frontend && npm install

      - name: Install build dependencies
        uses: amitie10g/install-package@v1
        with:
          apt: libgtk3-dev libwebkit-dev
          choco: webview2-runtime

      - name: Build Windows redistributable
        if: matrix.os == 'windows-latest'
        run: wails build -o euler-${{github.ref_name}}-win64.exe

      - name: Build Linux redistributable
        if: matrix.os == 'ubuntu-22.04'
        run: wails build -o euler-${{github.ref_name}}-linux

      - name: Build Mac redistributable
        if: matrix.os == 'macos-latest'
        run: wails build -o euler-${{github.ref_name}}-macos

      # Release artefact via GH releases
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "euler-*"
