// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetContents(arg1:string,arg2:string,arg3:boolean):Promise<Array<string>>;

export function GetTree(arg1:string):Promise<Array<string>>;
