// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetContents(arg1, arg2, arg3) {
  return window['go']['fsutil']['FSUtil']['GetContents'](arg1, arg2, arg3);
}

export function GetTree(arg1) {
  return window['go']['fsutil']['FSUtil']['GetTree'](arg1);
}
